version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: fluxo_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fluxo_caixa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fluxo_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fluxo_rabbit
    restart: always
    ports:
      - "5672:5672"     # Porta de mensagens
      - "15672:15672"   # UI de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - fluxo_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: fluxo_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - fluxo_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  fluxo_network:
    driver: bridge